[package]
name = "async_zip"
version = "0.0.9"
edition = "2021"
authors = ["Harry [hello@majored.pw]"]
repository = "https://github.com/Majored/rs-async-zip"
description = "An asynchronous ZIP archive reading/writing crate."
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/async_zip/"
homepage = "https://github.com/Majored/rs-async-zip"
keywords = ["async", "zip", "archive", "tokio"]
categories = ["asynchronous", "compression"]

[features]
full = ["date", "fs", "crc", "deflate", "bzip2", "lzma", "zstd", "xz"]

date = ["chrono"]
fs = []
crc = []

deflate = ["async-compression/deflate"]
bzip2 = ["async-compression/bzip2"]
lzma = ["async-compression/lzma"]
zstd = ["async-compression/zstd"]
xz = ["async-compression/xz"]

[dependencies]
crc32fast = "1.3.2"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["io-util", "fs"] }
pin-project = "1.0.12"

async-compression = { version = "0.3.15", default-features = false, features = ["tokio"], optional = true }
chrono = { version = "0.4.22", default-features = false, features = ["clock"], optional = true}

async_io_utilities = { git = "https://github.com/Majored/rs-async-io-utilities" }

[dev-dependencies]
sanitize-filename = "0.4.0"
tokio = { version = "1.21.2", features = ["full"] }
