[package]
name = "async_zip"
version = "0.0.9"
edition = "2021"
authors = ["Harry [hello@majored.pw]"]
repository = "https://github.com/Majored/rs-async-zip"
description = "An asynchronous ZIP archive reading/writing crate with a heavy focus on streaming support."
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/async_zip/"
homepage = "https://github.com/Majored/rs-async-zip"
keywords = ["async", "zip", "archive", "tokio"]
categories = ["asynchronous", "compression"]


[features]
default = ["deflate", "bzip2", "lzma", "zstd", "xz"]

deflate = ["async-compression/deflate"]
bzip2 = ["async-compression/bzip2"]
lzma = ["async-compression/lzma"]
zstd = ["async-compression/zstd"]
xz = ["async-compression/xz"]

[dependencies]
async-compression = { version = "0.3.15", default-features = false, features = ["tokio"] }
async_io_utilities = { git = "https://github.com/Majored/rs-async-io-utilities" }
tokio = { version = "1.21.2", features = ["io-util", "fs"] }
chrono = "0.4.22"
crc32fast = "1.3.2"
thiserror = "1.0.37"

[dev-dependencies]
tokio = { version = "1.21.2", features = ["full"] }
